// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scraper

import (
	"github.com/lightning-dabbler/sportscrape"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventDataScraper creates a new instance of MockEventDataScraper. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventDataScraper[M any, E any](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventDataScraper[M, E] {
	mock := &MockEventDataScraper[M, E]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventDataScraper is an autogenerated mock type for the EventDataScraper type
type MockEventDataScraper[M any, E any] struct {
	mock.Mock
}

type MockEventDataScraper_Expecter[M any, E any] struct {
	mock *mock.Mock
}

func (_m *MockEventDataScraper[M, E]) EXPECT() *MockEventDataScraper_Expecter[M, E] {
	return &MockEventDataScraper_Expecter[M, E]{mock: &_m.Mock}
}

// Feed provides a mock function for the type MockEventDataScraper
func (_mock *MockEventDataScraper[M, E]) Feed() sportscrape.Feed {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Feed")
	}

	var r0 sportscrape.Feed
	if returnFunc, ok := ret.Get(0).(func() sportscrape.Feed); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(sportscrape.Feed)
	}
	return r0
}

// MockEventDataScraper_Feed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Feed'
type MockEventDataScraper_Feed_Call[M any, E any] struct {
	*mock.Call
}

// Feed is a helper method to define mock.On call
func (_e *MockEventDataScraper_Expecter[M, E]) Feed() *MockEventDataScraper_Feed_Call[M, E] {
	return &MockEventDataScraper_Feed_Call[M, E]{Call: _e.mock.On("Feed")}
}

func (_c *MockEventDataScraper_Feed_Call[M, E]) Run(run func()) *MockEventDataScraper_Feed_Call[M, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventDataScraper_Feed_Call[M, E]) Return(feed sportscrape.Feed) *MockEventDataScraper_Feed_Call[M, E] {
	_c.Call.Return(feed)
	return _c
}

func (_c *MockEventDataScraper_Feed_Call[M, E]) RunAndReturn(run func() sportscrape.Feed) *MockEventDataScraper_Feed_Call[M, E] {
	_c.Call.Return(run)
	return _c
}

// Init provides a mock function for the type MockEventDataScraper
func (_mock *MockEventDataScraper[M, E]) Init() {
	_mock.Called()
	return
}

// MockEventDataScraper_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockEventDataScraper_Init_Call[M any, E any] struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
func (_e *MockEventDataScraper_Expecter[M, E]) Init() *MockEventDataScraper_Init_Call[M, E] {
	return &MockEventDataScraper_Init_Call[M, E]{Call: _e.mock.On("Init")}
}

func (_c *MockEventDataScraper_Init_Call[M, E]) Run(run func()) *MockEventDataScraper_Init_Call[M, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventDataScraper_Init_Call[M, E]) Return() *MockEventDataScraper_Init_Call[M, E] {
	_c.Call.Return()
	return _c
}

func (_c *MockEventDataScraper_Init_Call[M, E]) RunAndReturn(run func()) *MockEventDataScraper_Init_Call[M, E] {
	_c.Run(run)
	return _c
}

// Provider provides a mock function for the type MockEventDataScraper
func (_mock *MockEventDataScraper[M, E]) Provider() sportscrape.Provider {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Provider")
	}

	var r0 sportscrape.Provider
	if returnFunc, ok := ret.Get(0).(func() sportscrape.Provider); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(sportscrape.Provider)
	}
	return r0
}

// MockEventDataScraper_Provider_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provider'
type MockEventDataScraper_Provider_Call[M any, E any] struct {
	*mock.Call
}

// Provider is a helper method to define mock.On call
func (_e *MockEventDataScraper_Expecter[M, E]) Provider() *MockEventDataScraper_Provider_Call[M, E] {
	return &MockEventDataScraper_Provider_Call[M, E]{Call: _e.mock.On("Provider")}
}

func (_c *MockEventDataScraper_Provider_Call[M, E]) Run(run func()) *MockEventDataScraper_Provider_Call[M, E] {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEventDataScraper_Provider_Call[M, E]) Return(provider sportscrape.Provider) *MockEventDataScraper_Provider_Call[M, E] {
	_c.Call.Return(provider)
	return _c
}

func (_c *MockEventDataScraper_Provider_Call[M, E]) RunAndReturn(run func() sportscrape.Provider) *MockEventDataScraper_Provider_Call[M, E] {
	_c.Call.Return(run)
	return _c
}

// Scrape provides a mock function for the type MockEventDataScraper
func (_mock *MockEventDataScraper[M, E]) Scrape(matchup M) sportscrape.EventDataOutput[E] {
	ret := _mock.Called(matchup)

	if len(ret) == 0 {
		panic("no return value specified for Scrape")
	}

	var r0 sportscrape.EventDataOutput[E]
	if returnFunc, ok := ret.Get(0).(func(M) sportscrape.EventDataOutput[E]); ok {
		r0 = returnFunc(matchup)
	} else {
		r0 = ret.Get(0).(sportscrape.EventDataOutput[E])
	}
	return r0
}

// MockEventDataScraper_Scrape_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Scrape'
type MockEventDataScraper_Scrape_Call[M any, E any] struct {
	*mock.Call
}

// Scrape is a helper method to define mock.On call
//   - matchup M
func (_e *MockEventDataScraper_Expecter[M, E]) Scrape(matchup interface{}) *MockEventDataScraper_Scrape_Call[M, E] {
	return &MockEventDataScraper_Scrape_Call[M, E]{Call: _e.mock.On("Scrape", matchup)}
}

func (_c *MockEventDataScraper_Scrape_Call[M, E]) Run(run func(matchup M)) *MockEventDataScraper_Scrape_Call[M, E] {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 M
		if args[0] != nil {
			arg0 = args[0].(M)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventDataScraper_Scrape_Call[M, E]) Return(eventDataOutput sportscrape.EventDataOutput[E]) *MockEventDataScraper_Scrape_Call[M, E] {
	_c.Call.Return(eventDataOutput)
	return _c
}

func (_c *MockEventDataScraper_Scrape_Call[M, E]) RunAndReturn(run func(matchup M) sportscrape.EventDataOutput[E]) *MockEventDataScraper_Scrape_Call[M, E] {
	_c.Call.Return(run)
	return _c
}
