# https://vektra.github.io/mockery/latest/configuration/

filename: "mock_{{.InterfaceName}}.go"
dir: "internal/mocks/{{.SrcPackageName}}"
structname: "Mock{{.InterfaceName}}"
pkgname: '{{.SrcPackageName}}'

packages:
  github.com/lightning-dabbler/sportscrape/scraper:
    interfaces:
      MatchupScraper:
      EventDataScraper:
