# https://vektra.github.io/mockery/latest/configuration/

with-expecter: True
resolve-type-alias: False
issue-845-fix: True
disable-version-string: True

filename: "mock_{{.InterfaceName}}.go"
dir: "{{ .InterfaceDir }}/mocks"
mockname: "Mock{{.InterfaceName}}"
outpkg: "mock{{.PackageName}}"


packages:
  github.com/lightning-dabbler/sportscrape:
    interfaces:
      MatchupScraper:
      EventDataScraper:
