# https://vektra.github.io/mockery/latest/configuration/

filename: "mock_{{.InterfaceName}}.go"
dir: "{{ .InterfaceDir }}"
structname: "Mock{{.InterfaceName}}"
pkgname: '{{.SrcPackageName}}'

packages:
  github.com/lightning-dabbler/sportscrape:
    interfaces:
      MatchupScraper:
      EventDataScraper:
