package nfl

// statTypeDescriptions decodes the statType of a play's stats (driveChart.plays[].stats[].statType).
// The api doesn't document the codes; each description was verified against live data (2025 PRE/REG/POST and 2012 POST, 345 games):
//   - summing a code's count/yards per player (or team) per game reproduced the matching player-statistics
//     (or team-statistics) field exactly, e.g. 10 + 11 + 12 yards == rushingYards, or
//   - for codes without a matching box score field, the code's plays' descriptions (e.g. 37 only on punts "out of bounds").
//
// Codes not observed in that data are left out, so they get no description.
var statTypeDescriptions = map[int32]string{
	2:   "punt blocked",
	3:   "first down rushing",
	4:   "first down passing",
	5:   "first down penalty",
	6:   "third down converted",
	7:   "third down failed",
	8:   "fourth down converted",
	9:   "fourth down failed",
	10:  "rushing yards",
	11:  "rushing touchdown",
	12:  "rushing yards secondary runner",
	14:  "incomplete pass",
	15:  "passing yards",
	16:  "passing touchdown",
	19:  "interception thrown",
	20:  "sacked",
	21:  "receiving yards",
	22:  "receiving touchdown",
	23:  "lateral receiving yards",
	25:  "interception return yards",
	26:  "interception return touchdown",
	28:  "interception return touchdown secondary returner",
	29:  "punt",
	30:  "punt inside 20",
	31:  "punt into end zone returned",
	32:  "punt touchback",
	33:  "punt return yards",
	34:  "punt return touchdown",
	37:  "punt out of bounds",
	38:  "punt downed",
	39:  "punt fair catch",
	40:  "punt touchback receiving team",
	41:  "kickoff",
	42:  "kickoff inside 20",
	43:  "kickoff into end zone returned",
	44:  "kickoff touchback",
	45:  "kickoff return yards",
	46:  "kickoff return touchdown",
	49:  "kickoff out of bounds receiving team",
	50:  "kickoff fair catch",
	51:  "kickoff touchback receiving team",
	52:  "fumble forced",
	53:  "fumble not forced",
	54:  "fumble out of bounds",
	55:  "own fumble recovery yards",
	56:  "own fumble recovery touchdown",
	57:  "own fumble recovery yards aborted play",
	59:  "opponent fumble recovery yards",
	60:  "opponent fumble recovery touchdown",
	63:  "blocked kick recovery yards",
	64:  "blocked kick recovery touchdown",
	68:  "timeout",
	69:  "field goal missed",
	70:  "field goal made",
	71:  "field goal blocked",
	72:  "extra point good",
	73:  "extra point missed",
	74:  "extra point blocked",
	75:  "two point rush good",
	76:  "two point rush failed",
	77:  "two point pass good",
	78:  "two point pass failed",
	79:  "solo tackle",
	80:  "shared tackle",
	82:  "tackle assist",
	83:  "sack yards",
	84:  "half sack yards",
	85:  "pass defended",
	86:  "punt blocked by defense",
	87:  "extra point blocked by defense",
	88:  "field goal blocked by defense",
	89:  "safety",
	91:  "forced fumble",
	93:  "penalty",
	95:  "rush tackled for loss",
	102: "kickoff downed",
	104: "two point reception good",
	105: "two point reception failed",
	106: "fumble lost",
	107: "own kickoff recovery",
	108: "own kickoff recovery touchdown",
	110: "quarterback hit",
	111: "air yards completion",
	112: "air yards incompletion",
	113: "yards after catch",
	115: "target",
	120: "tackle for loss",
	402: "tackle for loss yards",
	403: "defensive two point attempt",
	404: "defensive two point conversion",
	410: "touchback kickoff distance",
	421: "kickoff short of landing zone receiving team",
	422: "kickoff landing zone touchback",
	424: "kickoff landing zone touchback receiving team",
	426: "kickoff end zone touchback",
	427: "kickoff end zone touchback receiving team",
}

// StatTypeDescription returns the description of a play stat's statType, nil when the code hasn't been verified
func StatTypeDescription(statType int32) *string {
	if description, exists := statTypeDescriptions[statType]; exists {
		return &description
	}
	return nil
}
