// Code generated by mockery. DO NOT EDIT.

package mocksportsreferenceutil

import mock "github.com/stretchr/testify/mock"

// MockBoxScoreProcessor is an autogenerated mock type for the BoxScoreProcessor type
type MockBoxScoreProcessor struct {
	mock.Mock
}

type MockBoxScoreProcessor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBoxScoreProcessor) EXPECT() *MockBoxScoreProcessor_Expecter {
	return &MockBoxScoreProcessor_Expecter{mock: &_m.Mock}
}

// GetSegmentBoxScoreStats provides a mock function with given fields: matchup
func (_m *MockBoxScoreProcessor) GetSegmentBoxScoreStats(matchup interface{}) []interface{} {
	ret := _m.Called(matchup)

	if len(ret) == 0 {
		panic("no return value specified for GetSegmentBoxScoreStats")
	}

	var r0 []interface{}
	if rf, ok := ret.Get(0).(func(interface{}) []interface{}); ok {
		r0 = rf(matchup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]interface{})
		}
	}

	return r0
}

// MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSegmentBoxScoreStats'
type MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call struct {
	*mock.Call
}

// GetSegmentBoxScoreStats is a helper method to define mock.On call
//   - matchup interface{}
func (_e *MockBoxScoreProcessor_Expecter) GetSegmentBoxScoreStats(matchup interface{}) *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call {
	return &MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call{Call: _e.mock.On("GetSegmentBoxScoreStats", matchup)}
}

func (_c *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call) Run(run func(matchup interface{})) *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(interface{}))
	})
	return _c
}

func (_c *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call) Return(_a0 []interface{}) *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call) RunAndReturn(run func(interface{}) []interface{}) *MockBoxScoreProcessor_GetSegmentBoxScoreStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockBoxScoreProcessor creates a new instance of MockBoxScoreProcessor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBoxScoreProcessor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBoxScoreProcessor {
	mock := &MockBoxScoreProcessor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
