name: Install Go
description: Installs Go

inputs:
  go-version:
    description: The go version to install
    default: "1.24.0"

runs:
  using: composite
  steps:
    - name: Install go ${{inputs.go-version}}
      uses: actions/setup-go@v5
      with:
        go-version: ${{inputs.go-version}}
    - name: Go version
      run: go version
      shell: bash
