name: Unit tests

on:
  push:
    branches-ignore: [main]
    paths:
      - 'go.mod'
      - 'go.sum'
      - 'util/**'
      - 'dataprovider/**'
      - '.github/workflows/unit-tests.yml'
      - '.github/actions/setup-go/actions.yml'

jobs:
  unit-tests:
    name: Run unit tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Install Go
        uses: ./.github/actions/setup-go
        with:
          go-version: '1.24.2'
      - name: Run unit tests
        run: make unit-tests
      - name: Archive unit test output and coverage
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-artifacts
          path: |
            coverage.out
            coverage.html
          retention-days: 30
